export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const ADD_SHIP = 'ADD_SHIP'
export const ADD_ITEM = 'ADD_ITEM'
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE'
export const LOAD_MONSTER = 'LOAD_MONSTER'
export const UNLOAD_MONSTER = 'UNLOAD MONSTER'
